### ISSUE TITLE
[QUESTION] - Other UI Libs

### ISSUE THREAD

**Issue by go4cas** [ais-one/cookbook#69]
@ais-one, the latest release looks pretty solid!

I was wondering how deeply integrated is Vuetify into vue-crud-x? How easy/difficult would it be to use another component library (like [iview](https://www.iviewui.com/), [element](https://element.eleme.io/#/en-US), [vue-ant](https://vue.ant.design/docs/vue/introduce/), etc)?

**Comment by ais-one** [comment]
Now not so difficult.

I indicated the places in the VueCrudX to change...

Planning to add ant when I have time... Vue and ant paging sorting filter
event is a bit different, but can be handled.

If need information faster, I am in the telegram group... @vuejssg

**Comment by go4cas** [comment]
@ais-one, any idea when ant would be implemented?

**Comment by ais-one** [comment]
I will try out next month... this month was really bz

**Comment by ais-one** [comment]
Now that things seem abit more stable, I would like to explore using another UI library such as Ant Design

**Comment by go4cas** [comment]
@ais-one, good to see the regular releases! Any idea more or less when the Ant Design release will be available?

**Comment by ais-one** [comment]
Hi,

These few days, I am working on backend.

Then frontend...

1. Making framework agnostic web components such as loading overlay...

2. Then design and implement for multi UI framework starting with Ant
Design!

**Comment by go4cas** [comment]
Hi @ais-one ... great changes with 0.30! Any progress with the Ant Design version?

**Comment by ais-one** [comment]
Hi, yes finally... will be moving on to Ant Design...

I need to try and reduce as much dependancy on any UI framework. Fortunately, Ant Design and Vuetify have pagination included with the data tables.

Bootstrap and I think Buefy does not have. Those will consider later.

**Comment by ais-one** [comment]
trying to get ant-design-vue to work with vue 3...

**Comment by ais-one** [comment]
https://medium.com/@eauditory3/ant-design-or-elephant-design-a03c19549553

Ant design is feature rich but seems bloated, even with tree shaking, thinking of really looking out for some other alternative...

**Comment by ais-one** [comment]
We may revisit Ant Design...

https://2x.antdv.com/docs/vue/migration-v2/

Hopefully momentJS is no longer a dependency there...

**Comment by ais-one** [comment]
overtaken by events
