### ISSUE TITLE
Question: Possible to auto-generate CRUD components from OpenAPI spec?

### ISSUE THREAD

**Issue by BusterNeece** [ais-one/cookbook#81]
Hello!

I just stumbled upon this library, and it feels like it would be immensely helpful in my development process.

I'm curious, though, whether there's any component of this application that can automatically generate components (or pages, or views, or whatever you call it) for each of the endpoints exposed by an OpenAPI spec document.

I noticed that the example servers expose their own OpenAPI spec doc, but it appears that the demos use a predefined example data model that isn't automatically generated from that spec.

Any assistance would be much appreciated!

**Comment by ais-one** [comment]
Hi I will look into this. In Java Spring boot this is possible, but in NodeJS so far I found documenting the routes to be most efficient AFAIK...

I had been looking at https://dredd.org/en/latest/

But it seems to only support OAS2, OAS3 does not seem to be ready

**Comment by ais-one** [comment]
Looking into generating the documentation and testing from code instead for now...

**Comment by ais-one** [comment]
This one will do it... you try this out, requires TS. I will be looking out for one that uses JSDoc... generate OAI docs only.

https://github.com/lukeautry/tsoa

Closing this issue
